"""Build the Windows x64 PrismCanvas one-file executable.

This script uses only the Python standard library. Run it with the isolated
Python environment that already has the pinned PyInstaller version installed.
"""

from __future__ import annotations

import argparse
import ast
import re
import struct
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PYINSTALLER_VERSION = "6.22.2"
EXECUTABLE_NAME = "PrismCanvas"
PRODUCT_NAME = "棱光 PrismCanvas"
FILE_DESCRIPTION = "棱光 PrismCanvas 本地 AI 创作画布"


def read_project_version(source: Path | None = None) -> str:
    """Read the literal __version__ assignment without importing the package."""
    source = source or ROOT / "frameweave" / "__init__.py"
    module = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
    values = []
    for statement in module.body:
        if isinstance(statement, ast.Assign):
            targets = statement.targets
        elif isinstance(statement, ast.AnnAssign):
            targets = [statement.target]
        else:
            continue
        if any(isinstance(target, ast.Name) and target.id == "__version__" for target in targets):
            try:
                values.append(ast.literal_eval(statement.value))
            except (ValueError, TypeError) as exc:
                raise ValueError("__version__ must be a literal string") from exc
    if len(values) != 1 or not isinstance(values[0], str):
        raise ValueError(f"expected one literal __version__ string in {source}")
    return values[0]


def windows_version_tuple(version: str) -> tuple[int, int, int, int]:
    """Convert a dotted numeric release to Windows' four 16-bit components."""
    if not re.fullmatch(r"\d+(?:\.\d+){0,3}", version):
        raise ValueError(f"Windows file version must contain only 1 to 4 numeric components: {version!r}")
    parts = [int(part) for part in version.split(".")]
    if any(part > 0xFFFF for part in parts):
        raise ValueError(f"Windows file version components must be at most 65535: {version!r}")
    return tuple((parts + [0, 0, 0, 0])[:4])  # type: ignore[return-value]


def make_version_resource(version: str) -> str:
    """Return PyInstaller's UTF-8 Version resource source for this release."""
    parts = windows_version_tuple(version)
    numeric = f"({parts[0]}, {parts[1]}, {parts[2]}, {parts[3]})"
    strings = (
        ("CompanyName", "NOXEVYR"),
        ("FileDescription", FILE_DESCRIPTION),
        ("FileVersion", version),
        ("InternalName", EXECUTABLE_NAME),
        ("LegalCopyright", "Copyright © NOXEVYR"),
        ("OriginalFilename", f"{EXECUTABLE_NAME}.exe"),
        ("ProductName", PRODUCT_NAME),
        ("ProductVersion", version),
    )
    string_rows = "\n".join(
        f"            StringStruct({key!r}, {value!r})," for key, value in strings
    )
    return f"""# UTF-8 Windows version resource generated by tools/build_windows.py.
VSVersionInfo(
    ffi=FixedFileInfo(
        filevers={numeric},
        prodvers={numeric},
        mask=0x3F,
        flags=0x0,
        OS=0x40004,
        fileType=0x1,
        subtype=0x0,
        date=(0, 0),
    ),
    kids=[
        StringFileInfo([
            StringTable(
                '080404B0',
                [
{string_rows}
                ],
            ),
        ]),
        VarFileInfo([VarStruct('Translation', [2052, 1200])]),
    ],
)
"""


def project_path(path: Path) -> Path:
    """Resolve relative CLI paths from the repository, independent of cwd."""
    if not path.is_absolute():
        path = ROOT / path
    return path.resolve()


def _overlaps(first: Path, second: Path) -> bool:
    return first == second or first.is_relative_to(second) or second.is_relative_to(first)


def pyinstaller_arguments(version_file: Path, output_dir: Path, build_dir: Path) -> list[str]:
    """Return stable PyInstaller arguments; no PyInstaller import is needed."""
    return [
        "-m", "PyInstaller",
        "--noconfirm",
        "--clean",
        "--onefile",
        "--windowed",
        "--name", EXECUTABLE_NAME,
        "--specpath", str(build_dir),
        "--icon", str(ROOT / "assets" / "frameweave.ico"),
        "--add-data", f"{ROOT / 'web'};web",
        "--version-file", str(version_file),
        "--distpath", str(output_dir),
        "--workpath", str(build_dir / "work"),
        str(ROOT / "launch.py"),
    ]


def _check_pyinstaller() -> None:
    result = subprocess.run(
        [sys.executable, "-m", "PyInstaller", "--version"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    actual = result.stdout.strip()
    if actual != PYINSTALLER_VERSION:
        raise RuntimeError(
            f"需要 PyInstaller {PYINSTALLER_VERSION}，当前环境报告 {actual or '未知版本'}；"
            "请使用已准备好的构建解释器，不要由此脚本安装依赖。"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="使用现有隔离环境构建 PrismCanvas Windows x64 候选包。")
    parser.add_argument(
        "--output-dir", type=Path, default=ROOT / "dist",
        help="EXE 输出目录（默认仓库 dist/；相对路径从仓库根解析）",
    )
    parser.add_argument(
        "--build-dir", type=Path, default=ROOT / "build",
        help="PyInstaller 临时构建目录（默认仓库 build/；相对路径从仓库根解析）",
    )
    args = parser.parse_args(argv)

    if sys.platform != "win32":
        parser.error("Windows 便携包必须在 Windows 上构建。")
    if sys.version_info < (3, 11):
        parser.error("构建要求 Python 3.11 或更高版本。")
    if struct.calcsize("P") != 8:
        parser.error("Windows x64 便携包要求 64 位 Python 解释器。")

    output_dir = project_path(args.output_dir)
    build_dir = project_path(args.build_dir)
    if _overlaps(output_dir, build_dir):
        parser.error("--output-dir 和 --build-dir 必须是互不嵌套的独立目录。")
    if output_dir.exists():
        if not output_dir.is_dir():
            parser.error(f"--output-dir 不是目录：{output_dir}")
        if next(output_dir.iterdir(), None) is not None:
            parser.error(f"--output-dir 必须为空，以保留已有文件：{output_dir}")

    version = read_project_version()
    windows_version_tuple(version)
    _check_pyinstaller()
    output_dir.mkdir(parents=True, exist_ok=True)
    build_dir.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="prismcanvas-version-") as temporary:
        version_file = Path(temporary) / "version.txt"
        version_file.write_text(make_version_resource(version), encoding="utf-8", newline="\n")
        with tempfile.TemporaryDirectory(prefix="prismcanvas-build-", dir=build_dir) as temporary_build:
            subprocess.run(
                [sys.executable, *pyinstaller_arguments(version_file, output_dir, Path(temporary_build))],
                cwd=ROOT,
                check=True,
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
